
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;
import javax.swing.JOptionPane;


/**
 *
 * @author Witsarut
 */
public class MyFormApp extends javax.swing.JFrame {

    /**
     * Creates new form MyFormApp
     */
    public MyFormApp() {
        initComponents();
        listIngredients.setVisible(false);
        jScrollPane1.setVisible(false);
        searchTab.setEnabled(false);
        menuPage.setVisible(false);
        topicMealbarn.setVisible(false);
        bg.setVisible(false);
        listMenuPage.setVisible(false);
        percentMenuPage.setVisible(false);
        ingredientPage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTab = new javax.swing.JButton();
        searchTab = new javax.swing.JButton();
        topicMealbarn = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        ingredientPage = new javax.swing.JPanel();
        percentMenuPage = new javax.swing.JPanel();
        percentMenu = new javax.swing.JPanel();
        menuPic2 = new javax.swing.JLabel();
        menuName2 = new javax.swing.JLabel();
        menuBt2 = new javax.swing.JButton();
        percentValue = new javax.swing.JLabel();
        percentMenu1 = new javax.swing.JPanel();
        menuPic3 = new javax.swing.JLabel();
        menuName3 = new javax.swing.JLabel();
        menuBt3 = new javax.swing.JButton();
        percentValue1 = new javax.swing.JLabel();
        listMenuPage = new javax.swing.JPanel();
        listMenu = new javax.swing.JPanel();
        menuPic = new javax.swing.JLabel();
        menuName = new javax.swing.JLabel();
        menuBt = new javax.swing.JButton();
        listMenu1 = new javax.swing.JPanel();
        menuPic1 = new javax.swing.JLabel();
        menuName1 = new javax.swing.JLabel();
        menuBt1 = new javax.swing.JButton();
        menuPage = new javax.swing.JPanel();
        appetizerPic = new javax.swing.JLabel();
        appetizerBt = new javax.swing.JButton();
        dessertPic = new javax.swing.JLabel();
        dessertBt = new javax.swing.JButton();
        maincoursePic = new javax.swing.JLabel();
        maincourseBt = new javax.swing.JButton();
        drinkPic = new javax.swing.JLabel();
        drinkBt = new javax.swing.JButton();
        soupPic = new javax.swing.JLabel();
        soupBt = new javax.swing.JButton();
        searchPage = new javax.swing.JPanel();
        topicMealbarnSearchPage = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        ingredients = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listIngredients = new javax.swing.JList<>();
        typeIngredient = new javax.swing.JTextField();
        bgSearchPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MEALBARN");
        getContentPane().setLayout(null);

        menuTab.setText("MENU");
        menuTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTabActionPerformed(evt);
            }
        });
        getContentPane().add(menuTab);
        menuTab.setBounds(933, 10, 80, 30);

        searchTab.setText("SEARCH");
        searchTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTabActionPerformed(evt);
            }
        });
        getContentPane().add(searchTab);
        searchTab.setBounds(843, 10, 90, 30);

        topicMealbarn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/mealbarn copy.png"))); // NOI18N
        getContentPane().add(topicMealbarn);
        topicMealbarn.setBounds(310, 40, 400, 100);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/test-bg.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1030, 190);

        ingredientPage.setLayout(null);
        getContentPane().add(ingredientPage);
        ingredientPage.setBounds(0, 0, 1024, 621);

        percentMenuPage.setLayout(null);

        percentMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        percentMenu.setLayout(null);

        menuPic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/appe.jpg"))); // NOI18N
        percentMenu.add(menuPic2);
        menuPic2.setBounds(40, 10, 150, 130);

        menuName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuName2.setText("MAMANAJA");
        percentMenu.add(menuName2);
        menuName2.setBounds(250, 10, 100, 40);

        menuBt2.setText("Click");
        percentMenu.add(menuBt2);
        menuBt2.setBounds(250, 100, 90, 30);

        percentValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        percentValue.setText("50 %");
        percentMenu.add(percentValue);
        percentValue.setBounds(280, 60, 50, 20);

        percentMenuPage.add(percentMenu);
        percentMenu.setBounds(560, 270, 420, 150);

        percentMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        percentMenu1.setLayout(null);

        menuPic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/appe.jpg"))); // NOI18N
        percentMenu1.add(menuPic3);
        menuPic3.setBounds(40, 10, 150, 130);

        menuName3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuName3.setText("MAMANAJA");
        percentMenu1.add(menuName3);
        menuName3.setBounds(250, 10, 100, 40);

        menuBt3.setText("Click");
        menuBt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBt3ActionPerformed(evt);
            }
        });
        percentMenu1.add(menuBt3);
        menuBt3.setBounds(250, 100, 90, 30);

        percentValue1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        percentValue1.setText("50 %");
        percentMenu1.add(percentValue1);
        percentValue1.setBounds(280, 60, 50, 20);

        percentMenuPage.add(percentMenu1);
        percentMenu1.setBounds(50, 270, 420, 150);

        getContentPane().add(percentMenuPage);
        percentMenuPage.setBounds(0, 0, 1024, 621);

        listMenuPage.setLayout(null);

        listMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listMenu.setLayout(null);

        menuPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/appe.jpg"))); // NOI18N
        listMenu.add(menuPic);
        menuPic.setBounds(40, 10, 150, 130);

        menuName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuName.setText("MAMANAJA");
        listMenu.add(menuName);
        menuName.setBounds(250, 20, 100, 40);

        menuBt.setText("Click");
        listMenu.add(menuBt);
        menuBt.setBounds(250, 80, 90, 30);

        listMenuPage.add(listMenu);
        listMenu.setBounds(550, 270, 420, 150);

        listMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listMenu1.setLayout(null);

        menuPic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/appe.jpg"))); // NOI18N
        listMenu1.add(menuPic1);
        menuPic1.setBounds(40, 10, 150, 130);

        menuName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuName1.setText("MAMANAJA");
        listMenu1.add(menuName1);
        menuName1.setBounds(250, 20, 100, 40);

        menuBt1.setText("Click");
        listMenu1.add(menuBt1);
        menuBt1.setBounds(250, 80, 90, 30);

        listMenuPage.add(listMenu1);
        listMenu1.setBounds(50, 270, 420, 150);

        getContentPane().add(listMenuPage);
        listMenuPage.setBounds(0, 0, 1024, 621);

        menuPage.setLayout(null);

        appetizerPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/appe.jpg"))); // NOI18N
        menuPage.add(appetizerPic);
        appetizerPic.setBounds(40, 200, 290, 150);

        appetizerBt.setText("APPETIZER");
        appetizerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appetizerBtActionPerformed(evt);
            }
        });
        menuPage.add(appetizerBt);
        appetizerBt.setBounds(140, 360, 100, 40);

        dessertPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/dess.jpg"))); // NOI18N
        menuPage.add(dessertPic);
        dessertPic.setBounds(40, 420, 290, 140);

        dessertBt.setText("DESSERT");
        dessertBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertBtActionPerformed(evt);
            }
        });
        menuPage.add(dessertBt);
        dessertBt.setBounds(140, 570, 110, 40);

        maincoursePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/mainc.jpg"))); // NOI18N
        menuPage.add(maincoursePic);
        maincoursePic.setBounds(360, 200, 290, 150);

        maincourseBt.setText("MAINCOURSE");
        maincourseBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maincourseBtActionPerformed(evt);
            }
        });
        menuPage.add(maincourseBt);
        maincourseBt.setBounds(440, 360, 120, 40);

        drinkPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/drink.jpg"))); // NOI18N
        menuPage.add(drinkPic);
        drinkPic.setBounds(360, 420, 290, 140);

        drinkBt.setText("DRINK");
        drinkBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkBtActionPerformed(evt);
            }
        });
        menuPage.add(drinkBt);
        drinkBt.setBounds(450, 570, 90, 40);

        soupPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/soup.jpg"))); // NOI18N
        menuPage.add(soupPic);
        soupPic.setBounds(690, 200, 300, 150);

        soupBt.setText("SOUP");
        soupBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soupBtActionPerformed(evt);
            }
        });
        menuPage.add(soupBt);
        soupBt.setBounds(800, 360, 80, 40);

        getContentPane().add(menuPage);
        menuPage.setBounds(0, 0, 1024, 621);

        searchPage.setLayout(null);

        topicMealbarnSearchPage.setForeground(new java.awt.Color(255, 255, 255));
        topicMealbarnSearchPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/mealbarn copy.png"))); // NOI18N
        topicMealbarnSearchPage.setText("lpfdldfpldf");
        searchPage.add(topicMealbarnSearchPage);
        topicMealbarnSearchPage.setBounds(300, 80, 400, 110);

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        searchPage.add(btnSubmit);
        btnSubmit.setBounds(440, 540, 100, 30);

        ingredients.setBackground(new java.awt.Color(255, 255, 255));
        searchPage.add(ingredients);
        ingredients.setBounds(150, 400, 750, 70);

        listIngredients.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listIngredients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listIngredients.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listIngredientsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listIngredients);

        searchPage.add(jScrollPane1);
        jScrollPane1.setBounds(200, 260, 650, 110);

        typeIngredient.setText("Type your ingredients here");
        typeIngredient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                typeIngredientKeyTyped(evt);
            }
        });
        searchPage.add(typeIngredient);
        typeIngredient.setBounds(200, 220, 650, 30);

        bgSearchPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/test-bg.jpg"))); // NOI18N
        searchPage.add(bgSearchPage);
        bgSearchPage.setBounds(0, 0, 1050, 620);

        getContentPane().add(searchPage);
        searchPage.setBounds(0, 0, 1024, 621);

        setBounds(0, 0, 1040, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        searchPage.setVisible(false);
        topicMealbarn.setVisible(true);
        bg.setVisible(true);
        searchTab.setEnabled(true);
        percentMenuPage.setVisible(true);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void listIngredientsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listIngredientsValueChanged
        // TODO add your handling code here:
        ingredients.setText(listIngredients.getSelectedValue());
    }//GEN-LAST:event_listIngredientsValueChanged

    private void searchTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTabActionPerformed
        // TODO add your handling code here:
        menuTab.setEnabled(true);
        searchTab.setEnabled(false);
        searchPage.setVisible(true);
        menuPage.setVisible(false);
        topicMealbarn.setVisible(false);
        bg.setVisible(false);
        listMenuPage.setVisible(false);
        percentMenuPage.setVisible(false);
        ingredientPage.setVisible(false);
    }//GEN-LAST:event_searchTabActionPerformed

    private void menuTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTabActionPerformed
        // TODO add your handling code here:
        menuTab.setEnabled(false);
        searchTab.setEnabled(true);
        searchPage.setVisible(false);
        menuPage.setVisible(true);
        topicMealbarn.setVisible(true);
        bg.setVisible(true);
        listMenuPage.setVisible(false);
        percentMenuPage.setVisible(false);
        ingredientPage.setVisible(false);
    }//GEN-LAST:event_menuTabActionPerformed

    private void typeIngredientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeIngredientKeyTyped
        // TODO add your handling code here:
        jScrollPane1.setVisible(true);
        listIngredients.setVisible(true);
    }//GEN-LAST:event_typeIngredientKeyTyped

    private void appetizerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appetizerBtActionPerformed
        // TODO add your handling code here:
        menuPage.setVisible(false);
        topicMealbarn.setVisible(true);
        bg.setVisible(true);
        menuTab.setEnabled(true);
        listMenuPage.setVisible(true);
    }//GEN-LAST:event_appetizerBtActionPerformed

    private void maincourseBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maincourseBtActionPerformed
        // TODO add your handling code here:
        menuPage.setVisible(false);
        topicMealbarn.setVisible(true);
        bg.setVisible(true);
        menuTab.setEnabled(true);
        listMenuPage.setVisible(true);
    }//GEN-LAST:event_maincourseBtActionPerformed

    private void soupBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soupBtActionPerformed
        // TODO add your handling code here:
        menuPage.setVisible(false);
        topicMealbarn.setVisible(true);
        bg.setVisible(true);
        menuTab.setEnabled(true);
        listMenuPage.setVisible(true);
    }//GEN-LAST:event_soupBtActionPerformed

    private void dessertBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertBtActionPerformed
        // TODO add your handling code here:
        menuPage.setVisible(false);
        topicMealbarn.setVisible(true);
        bg.setVisible(true);
        menuTab.setEnabled(true);
        listMenuPage.setVisible(true);
    }//GEN-LAST:event_dessertBtActionPerformed

    private void drinkBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkBtActionPerformed
        // TODO add your handling code here:
        menuPage.setVisible(false);
        topicMealbarn.setVisible(true);
        bg.setVisible(true);
        menuTab.setEnabled(true);
        listMenuPage.setVisible(true);
    }//GEN-LAST:event_drinkBtActionPerformed

    private void menuBt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBt3ActionPerformed
        // TODO add your handling code here:
         ingredientPage.setVisible(true);
         percentMenuPage.setVisible(false);
    }//GEN-LAST:event_menuBt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFormApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFormApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFormApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFormApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFormApp().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appetizerBt;
    private javax.swing.JLabel appetizerPic;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bgSearchPage;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton dessertBt;
    private javax.swing.JLabel dessertPic;
    private javax.swing.JButton drinkBt;
    private javax.swing.JLabel drinkPic;
    private javax.swing.JPanel ingredientPage;
    private javax.swing.JLabel ingredients;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listIngredients;
    private javax.swing.JPanel listMenu;
    private javax.swing.JPanel listMenu1;
    private javax.swing.JPanel listMenuPage;
    private javax.swing.JButton maincourseBt;
    private javax.swing.JLabel maincoursePic;
    private javax.swing.JButton menuBt;
    private javax.swing.JButton menuBt1;
    private javax.swing.JButton menuBt2;
    private javax.swing.JButton menuBt3;
    private javax.swing.JLabel menuName;
    private javax.swing.JLabel menuName1;
    private javax.swing.JLabel menuName2;
    private javax.swing.JLabel menuName3;
    private javax.swing.JPanel menuPage;
    private javax.swing.JLabel menuPic;
    private javax.swing.JLabel menuPic1;
    private javax.swing.JLabel menuPic2;
    private javax.swing.JLabel menuPic3;
    private javax.swing.JButton menuTab;
    private javax.swing.JPanel percentMenu;
    private javax.swing.JPanel percentMenu1;
    private javax.swing.JPanel percentMenuPage;
    private javax.swing.JLabel percentValue;
    private javax.swing.JLabel percentValue1;
    private javax.swing.JPanel searchPage;
    private javax.swing.JButton searchTab;
    private javax.swing.JButton soupBt;
    private javax.swing.JLabel soupPic;
    private javax.swing.JLabel topicMealbarn;
    private javax.swing.JLabel topicMealbarnSearchPage;
    private javax.swing.JTextField typeIngredient;
    // End of variables declaration//GEN-END:variables
}
